// <auto-generated />
using System;
using IsDB.Hospitality.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsDB.Hospitality.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501212329_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GuestId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResolvedByStaffId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("ResolvedByStaffId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumLeadTimeHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventTitle = "IsDB Annual Meetings 2025",
                            MinimumLeadTimeHours = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.CarClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarClasses");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.ChecklistCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChecklistItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompletedByStaffId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("CompletedByStaffId");

                    b.HasIndex("GuestId", "ChecklistItemId")
                        .IsUnique();

                    b.ToTable("ChecklistCompletions");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.DepartureRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisclaimerAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HotelOptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManageToken")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PickupDayOptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PickupHourOptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HotelOptionId");

                    b.HasIndex("ManageToken")
                        .IsUnique();

                    b.HasIndex("PickupDayOptionId");

                    b.HasIndex("PickupHourOptionId");

                    b.ToTable("DepartureRequests");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.EventsAirConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoSyncEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSyncDeactivatedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSyncMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSyncRecordsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EventsAirConfigs");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.EventsAirSyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EventsAirSyncLogs");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualDeparture")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualGate")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualTerminal")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AirlineIataCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalPortIataCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalPortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePortIataCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastTrackedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedicatedCar")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeservedCarClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventsAirContactId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HotelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("InboundStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutboundStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RankValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReceivedByEmbassyTeam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationTypeName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAccessibility")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialRequirements")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeservedCarClassId");

                    b.HasIndex("EventsAirContactId")
                        .IsUnique();

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.GuestStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedByName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChangedByRole")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ChangedByStaffId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRolledBack")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RolledBackByHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Track")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByStaffId");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestStatusHistories");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.HotelOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HotelOptions");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByStaffId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetRoles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByStaffId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.NotificationRead", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationId", "StaffUserId");

                    b.HasIndex("StaffUserId");

                    b.ToTable("NotificationReads");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.PickupDayOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PickupDayOptions");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.PickupHourOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PickupHourOptions");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.RegistrationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventsAirId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFromEventsAir")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelectedForSync")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegistrationTypes");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("StaffUsers");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.StaffUserRole", b =>
                {
                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("StaffUserId", "Role");

                    b.ToTable("StaffUserRoles");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.SyncFieldMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventsAirFieldGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncFieldMappings");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.SyncFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelectedForSync")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SyncFieldMappingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SyncFieldMappingId");

                    b.ToTable("SyncFieldValues");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.SyncRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncRecords");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.TravelBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirlineReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DelayReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gate")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArrival")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Itinerary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatClass")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Terminal")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Tickets")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("GuestId");

                    b.ToTable("TravelBookings");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BarcodeValue")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarClassId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentAssignmentType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CurrentGuestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeValue");

                    b.HasIndex("CarClassId");

                    b.HasIndex("CurrentGuestId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.VehicleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignedByStaffId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedArrivalTime")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnassignedByStaffId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByStaffId");

                    b.HasIndex("DriverId");

                    b.HasIndex("GuestId");

                    b.HasIndex("UnassignedByStaffId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleAssignments");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Alert", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.Guest", "Guest")
                        .WithMany("Alerts")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsDB.Hospitality.Domain.Entities.StaffUser", "ResolvedByStaff")
                        .WithMany()
                        .HasForeignKey("ResolvedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Guest");

                    b.Navigation("ResolvedByStaff");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.ChecklistCompletion", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.ChecklistItem", "ChecklistItem")
                        .WithMany("Completions")
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsDB.Hospitality.Domain.Entities.StaffUser", "CompletedByStaff")
                        .WithMany()
                        .HasForeignKey("CompletedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsDB.Hospitality.Domain.Entities.Guest", "Guest")
                        .WithMany("ChecklistCompletions")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("CompletedByStaff");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.DepartureRequest", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.HotelOption", "HotelOption")
                        .WithMany()
                        .HasForeignKey("HotelOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsDB.Hospitality.Domain.Entities.PickupDayOption", "PickupDayOption")
                        .WithMany()
                        .HasForeignKey("PickupDayOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsDB.Hospitality.Domain.Entities.PickupHourOption", "PickupHourOption")
                        .WithMany()
                        .HasForeignKey("PickupHourOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HotelOption");

                    b.Navigation("PickupDayOption");

                    b.Navigation("PickupHourOption");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Driver", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.Vehicle", "Vehicle")
                        .WithOne("Driver")
                        .HasForeignKey("IsDB.Hospitality.Domain.Entities.Driver", "VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Guest", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.CarClass", "DeservedCarClass")
                        .WithMany("Guests")
                        .HasForeignKey("DeservedCarClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeservedCarClass");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.GuestStatusHistory", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.StaffUser", "ChangedByStaff")
                        .WithMany()
                        .HasForeignKey("ChangedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsDB.Hospitality.Domain.Entities.Guest", "Guest")
                        .WithMany("StatusHistory")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByStaff");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Notification", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.StaffUser", "CreatedByStaff")
                        .WithMany()
                        .HasForeignKey("CreatedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByStaff");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.NotificationRead", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.Notification", "Notification")
                        .WithMany("Reads")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsDB.Hospitality.Domain.Entities.StaffUser", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.StaffUserRole", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.StaffUser", "StaffUser")
                        .WithMany("Roles")
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.SyncFieldValue", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.SyncFieldMapping", "SyncFieldMapping")
                        .WithMany("SelectedValues")
                        .HasForeignKey("SyncFieldMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncFieldMapping");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.TravelBooking", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.Flight", "Flight")
                        .WithMany("TravelBookings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsDB.Hospitality.Domain.Entities.Guest", "Guest")
                        .WithMany("TravelBookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.CarClass", "CarClass")
                        .WithMany("Vehicles")
                        .HasForeignKey("CarClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsDB.Hospitality.Domain.Entities.Guest", "CurrentGuest")
                        .WithMany()
                        .HasForeignKey("CurrentGuestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CarClass");

                    b.Navigation("CurrentGuest");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.VehicleAssignment", b =>
                {
                    b.HasOne("IsDB.Hospitality.Domain.Entities.StaffUser", "AssignedByStaff")
                        .WithMany()
                        .HasForeignKey("AssignedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsDB.Hospitality.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsDB.Hospitality.Domain.Entities.Guest", "Guest")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsDB.Hospitality.Domain.Entities.StaffUser", "UnassignedByStaff")
                        .WithMany()
                        .HasForeignKey("UnassignedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsDB.Hospitality.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Assignments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByStaff");

                    b.Navigation("Driver");

                    b.Navigation("Guest");

                    b.Navigation("UnassignedByStaff");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.CarClass", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.ChecklistItem", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Flight", b =>
                {
                    b.Navigation("TravelBookings");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Guest", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ChecklistCompletions");

                    b.Navigation("StatusHistory");

                    b.Navigation("TravelBookings");

                    b.Navigation("VehicleAssignments");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Notification", b =>
                {
                    b.Navigation("Reads");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.StaffUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.SyncFieldMapping", b =>
                {
                    b.Navigation("SelectedValues");
                });

            modelBuilder.Entity("IsDB.Hospitality.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
